"""
SAP SD Intelligent Agent Pipeline v4 — Production
====================================================
Two-model architecture:
  Model 1 (LLM_MODEL_1): understands question + generates ABAP query
  Model 2 (LLM_MODEL_2): executes MongoDB tools + formats final answer

Why two models:
  - Model 1 can be swapped to Claude API later for better classification
  - SAP/MongoDB data never touches Model 1 (only the question does)
  - Model 2 runs fully local always — data stays on-premise

Change models anytime via .env — no code changes needed:
  LLM_MODEL_1=qwen2.5:3b   → change to claude/llama3.1:8b later
  LLM_MODEL_2=qwen2.5:3b   → always local

Author  : Rohit Kumar
Project : SAP ERP RAG Pipeline — Keva Fragrances Internship
"""

import os
import re
import json
from typing import Annotated, TypedDict, Literal
from pymongo import MongoClient
from dotenv import load_dotenv
from langchain_ollama import OllamaEmbeddings, ChatOllama
from langchain_chroma import Chroma
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.messages import HumanMessage
from langgraph.graph import StateGraph, END
from langgraph.graph.message import add_messages

load_dotenv()

# ─── CONFIG — all from .env ───────────────────────────────────────────────────
MONGO_URI   = os.getenv("MONGO_URI")
DB_NAME     = os.getenv("DB_NAME")
OLLAMA_URL  = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
MODEL_1     = os.getenv("LLM_MODEL_1", "qwen2.5:3b")   # classify + ABAP
MODEL_2     = os.getenv("LLM_MODEL_2", "qwen2.5:3b")   # execute + format
EMBED_MODEL = os.getenv("EMBED_MODEL", "mxbai-embed-large")
TEMPERATURE = float(os.getenv("LLM_TEMPERATURE", "0.1"))

print(f"  Model 1 (classify + ABAP) : {MODEL_1}")
print(f"  Model 2 (execute + format): {MODEL_2}")
print(f"  Embed                     : {EMBED_MODEL}")

# ─── CONNECTIONS ──────────────────────────────────────────────────────────────
client   = MongoClient(MONGO_URI)
db       = client[DB_NAME]

# Model 1 — understands question, generates ABAP (can be cloud model later)
llm_1 = ChatOllama(model=MODEL_1, base_url=OLLAMA_URL, temperature=TEMPERATURE)

# Model 2 — executes queries, formats answers (always local, sees SAP data)
llm_2 = ChatOllama(model=MODEL_2, base_url=OLLAMA_URL, temperature=TEMPERATURE)

embeddings = OllamaEmbeddings(model=EMBED_MODEL, base_url=OLLAMA_URL)
vectordb   = Chroma(
    persist_directory="./chroma_db",
    embedding_function=embeddings,
    collection_name="sap_sd"
)

# ─── AGENT STATE ──────────────────────────────────────────────────────────────
class AgentState(TypedDict):
    question:     str
    intent:       str
    sub_type:     str
    params:       dict
    abap_query:   str          # generated by Model 1
    mongo_query:  str          # auto-generated from sub_type
    tool_result:  str          # generated by Model 2
    final_answer: str          # formatted by Model 2
    messages:     Annotated[list, add_messages]

# ══════════════════════════════════════════════════════════════════════════════
# NODE 1 — CLASSIFY + ABAP (Model 1)
# Model 1 reads only the question — no SAP data
# Returns: intent JSON + ABAP query
# ══════════════════════════════════════════════════════════════════════════════
CLASSIFY_PROMPT = """You are an SAP data expert. Given a business question, do two things:

1. Classify the intent as JSON
2. Generate the ABAP SELECT query for it

Intent types:
- "aggregate"  : rankings, growth %, totals, counts, comparisons over ALL records
- "lookup"     : specific document details (order SO123, customer C000001)
- "semantic"   : conceptual/descriptive (explain, compare, describe)

Sub-types for aggregate:
top_customers, top_products, customer_growth, product_margins,
company_product, manager_growth, order_status, delivery_status,
billing_status, revenue_by_fy, orders_above

SAP SD Tables for ABAP:
- VBAK: Sales Order Header (VBELN, ERDAT, AUART, KUNNR, NETWR, WAERS, VKORG, VTWEG, GBSTK, LIFSK, FAKSK)
- VBAP: Sales Order Items (VBELN, POSNR, MATNR, ARKTX, KWMENG, MEINS, NETPR, NETWR, WERKS, COST)
- VBRK: Billing Header (VBELN, FKDAT, FKART, KUNNR, NETWR, MWSBP, FKSTO, RFBSK, VKORG)
- VBRP: Billing Items (VBELN, POSNR, MATNR, ARKTX, FKIMG, VRKME, NETWR, NETPR, COST)
- KNA1: Customer Master (KUNNR, NAME1, ORT01, LAND1, REGIO, STCEG, BRSCH)
- LIKP: Delivery Header (VBELN, KUNNR, WADAT, WADAT_IST, LFGSX, VSTEL, BTGEW)
- LIPS: Delivery Items (VBELN, POSNR, MATNR, ARKTX, LFIMG, VRKME, WERKS)
- VBFA: Document Flow (VBELV, VBELN, VBTYP_N, VBTYP_V)

ABAP Rules:
- Start with REPORT z_sap_query.
- Use SELECT ... INTO TABLE @DATA(lt_result)
- Use GROUP BY for aggregations
- Use ORDER BY ... DESCENDING for rankings
- Use UP TO N ROWS for limits
- Add * comments

Return ONLY this format, nothing else:
INTENT_JSON: {{"intent":"...","sub_type":"...","params":{{"n":5,"fy1":"FY2023-24","fy2":"FY2024-25","threshold":20,"amount":null,"status":null,"entity_id":null}}}}
ABAP_QUERY:
<abap code here>

Question: {question}"""

def normalize_fiscal_years(params: dict, question: str = "") -> dict:
    """
    Extract FY directly from question if short notation detected.
    Overrides whatever model returned.
    """
    # find all short FY mentions in question e.g. FY24, FY 25
    short_fys = re.findall(r'\bFY\s*(\d{2})\b', question, re.I)
    
    if short_fys:
        # convert short FY to full format
        full_fys = []
        for yy in short_fys:
            year  = 2000 + int(yy)
            start = year - 1
            full_fys.append(f"FY{start}-{yy}")
        
        # assign fy1 and fy2 directly from question
        if len(full_fys) >= 1:
            params["fy1"] = full_fys[0]
        if len(full_fys) >= 2:
            params["fy2"] = full_fys[1]
        return params

    # no short FY in question — don't touch params
    return params

def node_classify(state: AgentState) -> AgentState:
    """Model 1 — two separate calls: classify first, then generate ABAP"""

    # ── Call 1: classify intent only (simple, reliable) ──────────────────────
    classify_prompt = PromptTemplate(
        template="""Classify this SAP business question. Return ONLY valid JSON.

Intent types:
- "aggregate"  : rankings, growth %, totals, counts, comparisons over ALL records
- "lookup"     : specific document (order SO123, customer C000001)
- "semantic"   : conceptual/descriptive (explain, compare, describe)

Sub-types for aggregate:
top_customers, top_products, customer_growth, product_margins,
company_product, manager_growth, order_status, delivery_status,
billing_status, revenue_by_fy, orders_above

Indian Fiscal Year rules (Apr 1 to Mar 31):
- FY format is always "FY<start_year>-<end_year_2digit>" e.g. "FY2023-24"
- "FY24" or "FY 24" means the year ENDING in 24, so start=2023 → "FY2023-24"
- "FY25" or "FY 25" means the year ENDING in 25, so start=2024 → "FY2024-25"
- "FY26" or "FY 26" means the year ENDING in 26, so start=2025 → "FY2025-26"
- General rule: if year mentioned is YY, fy = "FY20(YY-1)-YY"
- Always return full format like "FY2023-24", never just "FY24"

Params to extract:
- n         : number for top N (default 5)
- fy1       : first/earlier fiscal year in full format (default "FY2023-24")
- fy2       : second/later fiscal year in full format (default "FY2024-25")
- threshold : percentage for growth filter (default 20)
- amount    : numeric INR amount (null if not mentioned)
- status    : open/completed/pending/cleared (null if not mentioned)
- entity_id : document ID like SO00000086 (null if not mentioned)

Examples:
Q: "Which company product combination gets most revenue top 10"
A: {{"intent":"aggregate","sub_type":"company_product","params":{{"n":10,"fy1":"FY2023-24","fy2":"FY2024-25","threshold":20,"amount":null,"status":null,"entity_id":null}}}}

Q: "Which area managers have slowest growth in sales"
A: {{"intent":"aggregate","sub_type":"manager_growth","params":{{"n":5,"fy1":"FY2023-24","fy2":"FY2024-25","threshold":20,"amount":null,"status":null,"entity_id":null}}}}

Q: "Top 5 customers by invoiced value"
A: {{"intent":"aggregate","sub_type":"top_customers","params":{{"n":5,"fy1":"FY2023-24","fy2":"FY2024-25","threshold":20,"amount":null,"status":null,"entity_id":null}}}}

Q: "3 products with least margins"
A: {{"intent":"aggregate","sub_type":"product_margins","params":{{"n":3,"fy1":"FY2023-24","fy2":"FY2024-25","threshold":20,"amount":null,"status":null,"entity_id":null}}}}

Return ONLY this JSON, nothing else:
{{"intent":"...","sub_type":"...","params":{{"n":5,"fy1":"FY2023-24","fy2":"FY2024-25","threshold":20,"amount":null,"status":null,"entity_id":null}}}}

Question: {question}
JSON:""",
        input_variables=["question"]
    )
    raw = (classify_prompt | llm_1 | StrOutputParser()).invoke({"question": state["question"]})

    intent_data = {}
    try:
        m = re.search(r'\{.*\}', raw, re.DOTALL)
        intent_data = json.loads(m.group()) if m else {}
    except Exception:
        intent_data = {}

    # ── normalize fiscal years ─────────────────────────────────────────────
    if "params" in intent_data:
        intent_data["params"] = normalize_fiscal_years(intent_data["params"],
                                                       question=state["question"])

    # ── Call 2: generate ABAP separately ──────────────────────────────────────
    abap_prompt = PromptTemplate(
        template="""You are a senior SAP ABAP developer. Generate ABAP SELECT query.

SAP SD Tables:
- VBAK: Sales Order Header (VBELN, ERDAT, AUART, KUNNR, NETWR, WAERS, VKORG, VTWEG, GBSTK, LIFSK, FAKSK)
- VBAP: Sales Order Items (VBELN, POSNR, MATNR, ARKTX, KWMENG, MEINS, NETPR, NETWR, WERKS, COST)
- VBRK: Billing Header (VBELN, FKDAT, FKART, KUNNR, NETWR, MWSBP, FKSTO, RFBSK, VKORG)
- VBRP: Billing Items (VBELN, POSNR, MATNR, ARKTX, FKIMG, VRKME, NETWR, NETPR, COST)
- KNA1: Customer Master (KUNNR, NAME1, ORT01, LAND1, REGIO, STCEG, BRSCH)
- LIKP: Delivery Header (VBELN, KUNNR, WADAT, WADAT_IST, LFGSX, VSTEL, BTGEW)
- LIPS: Delivery Items (VBELN, POSNR, MATNR, ARKTX, LFIMG, VRKME, WERKS)
- VBFA: Document Flow (VBELV, VBELN, VBTYP_N, VBTYP_V)

Rules: REPORT z_sap_query. | INTO TABLE @DATA(lt_result) | GROUP BY | ORDER BY DESCENDING | UP TO N ROWS | add * comments | Return ONLY the code, no explanation text

Question: {question}
ABAP Query:""",
        input_variables=["question"]
    )
    abap = (abap_prompt | llm_1 | StrOutputParser()).invoke({"question": state["question"]})

    return {
        **state,
        "intent":     intent_data.get("intent",   "semantic"),
        "sub_type":   intent_data.get("sub_type", "general"),
        "params":     intent_data.get("params",   {}),
        "abap_query": abap,
        "mongo_query": "",
        "messages":   [HumanMessage(content=state["question"])]
    }

# ══════════════════════════════════════════════════════════════════════════════
# NODE 2A — AGGREGATE TOOL (Model 2)
# Model 2 runs MongoDB queries — sees SAP data, always local
# ══════════════════════════════════════════════════════════════════════════════
def get_mongo_query_text(sub_type: str, params: dict) -> str:
    """Returns MongoDB query as readable text — auto-generated, always accurate"""
    n      = params.get("n", 5)
    fy1    = params.get("fy1", "FY2023-24")
    fy2    = params.get("fy2", "FY2024-25")
    thresh = params.get("threshold", 20)
    amount = params.get("amount")
    status = params.get("status")

    queries = {
        "top_customers": f'''db["VBRK"].aggregate([
    {{"$match": {{"FKSTO": {{"$ne": "X"}}}}}},
    {{"$group": {{"_id": "$KUNNR", "NAME1": {{"$first": "$NAME1"}}, "total": {{"$sum": "$NETWR"}}}}}},
    {{"$sort": {{"total": -1}}}},
    {{"$limit": {n}}}
])''',
        "top_products": f'''db["VBAP"].aggregate([
    {{"$group": {{"_id": "$MATNR", "ARKTX": {{"$first": "$ARKTX"}},
                "qty": {{"$sum": "$KWMENG"}}, "revenue": {{"$sum": "$NETWR"}}}}}},
    {{"$sort": {{"qty": -1}}}},
    {{"$limit": {n}}}
])''',
        "customer_growth": f'''# Step 1 — FY1 revenue per customer
db["VBAK"].aggregate([
    {{"$match": {{"FISCAL_YEAR": "{fy1}"}}}},
    {{"$group": {{"_id": "$KUNNR", "NAME1": {{"$first": "$NAME1"}}, "rev": {{"$sum": "$NETWR"}}}}}}
])
# Step 2 — FY2 revenue per customer
db["VBAK"].aggregate([
    {{"$match": {{"FISCAL_YEAR": "{fy2}"}}}},
    {{"$group": {{"_id": "$KUNNR", "NAME1": {{"$first": "$NAME1"}}, "rev": {{"$sum": "$NETWR"}}}}}}
])
# Step 3 — Calculate growth % in Python, filter > {thresh}%''',
        "product_margins": f'''db["VBAP"].aggregate([
    {{"$group": {{"_id": "$MATNR", "ARKTX": {{"$first": "$ARKTX"}},
                "avg_margin": {{"$avg": "$MARGIN_PCT"}},
                "total_rev":  {{"$sum": "$NETWR"}}}}}},
    {{"$sort": {{"avg_margin": 1}}}},
    {{"$limit": {n}}}
])''',
        "company_product": f'''db["VBAP"].aggregate([
    {{"$group": {{
        "_id":     {{"kunnr": "$KUNNR", "matnr": "$MATNR"}},
        "NAME1":   {{"$first": "$NAME1"}},
        "ARKTX":   {{"$first": "$ARKTX"}},
        "revenue": {{"$sum": "$NETWR"}}
    }}}},
    {{"$sort": {{"revenue": -1}}}},
    {{"$limit": {n}}}
])''',
        "manager_growth": f'''# Step 1 — FY1 revenue per area manager
db["VBAK"].aggregate([
    {{"$match": {{"FISCAL_YEAR": "{fy1}"}}}},
    {{"$group": {{"_id": "$AREA_MGR", "rev": {{"$sum": "$NETWR"}}}}}}
])
# Step 2 — FY2 revenue per area manager
db["VBAK"].aggregate([
    {{"$match": {{"FISCAL_YEAR": "{fy2}"}}}},
    {{"$group": {{"_id": "$AREA_MGR", "rev": {{"$sum": "$NETWR"}}}}}}
])
# Step 3 — Sort by growth % ascending (slowest first)''',
        "order_status": f'''db["VBAK"].find(
    {{"GBSTK": "A"}},  # A=Open B=In-Process C=Completed
    {{"VBELN":1, "NAME1":1, "NETWR":1, "ERDAT":1, "FISCAL_YEAR":1, "_id":0}}
)''',
        "delivery_status": f'''db["LIKP"].find(
    {{"LFGSX": "A"}},  # A=Not Started B=Partial C=Completed
    {{"VBELN":1, "NAME1":1, "WADAT":1, "VBELN_VK":1, "_id":0}}
)''',
        "billing_status": f'''db["VBRK"].find(
    {{"RFBSK": "A", "FKSTO": {{"$ne": "X"}}}},
    {{"VBELN":1, "NAME1":1, "NETWR":1, "MWSBP":1, "ERDAT":1, "_id":0}}
)''',
        "revenue_by_fy": '''db["VBAK"].aggregate([
    {"$group": {"_id": "$FISCAL_YEAR", "total": {"$sum": "$NETWR"}, "count": {"$sum": 1}}},
    {"$sort": {"_id": 1}}
])''',
        "orders_above": f'''db["VBAK"].find(
    {{"NETWR": {{"$gt": {amount}}}, "GBSTK": "A"}},
    {{"VBELN":1, "NAME1":1, "NETWR":1, "VDATU":1, "_id":0}}
).sort("NETWR", -1)''',
    }
    return queries.get(sub_type, "# MongoDB query not defined for this sub_type")

def node_aggregate(state: AgentState) -> AgentState:
    p      = state["params"]
    sub    = state["sub_type"]
    mongo_q = get_mongo_query_text(sub, p) 
    n      = int(p.get("n") or 5)
    fy1    = str(p.get("fy1") or "FY2023-24")
    fy2    = str(p.get("fy2") or "FY2024-25")
    thresh = float(p.get("threshold") or 20)
    amount = p.get("amount")
    status = p.get("status")
    result = ""

    if sub == "top_customers":
        rows = list(db["VBRK"].aggregate([
            {"$match": {"FKSTO": {"$ne": "X"}}},
            {"$group": {"_id": "$KUNNR", "NAME1": {"$first": "$NAME1"}, "total": {"$sum": "$NETWR"}}},
            {"$sort": {"total": -1}}, {"$limit": n}
        ]))
        lines = [f"Top {n} customers by total invoiced value:\n"]
        for i, r in enumerate(rows, 1):
            lines.append(f"  {i}. {r['NAME1']:35s}  ₹{r['total']:>15,.2f}")
        result = "\n".join(lines)

    elif sub == "top_products":
        rows = list(db["VBAP"].aggregate([
            {"$group": {"_id": "$MATNR", "ARKTX": {"$first": "$ARKTX"},
                        "qty": {"$sum": "$KWMENG"}, "revenue": {"$sum": "$NETWR"}}},
            {"$sort": {"qty": -1}}, {"$limit": n}
        ]))
        lines = [f"Top {n} selling products by quantity:\n"]
        for i, r in enumerate(rows, 1):
            lines.append(f"  {i}. {r['ARKTX']:40s}  Qty: {r['qty']:>6,}  |  ₹{r['revenue']:>15,.2f}")
        result = "\n".join(lines)

    elif sub == "customer_growth":
        d1 = {r["_id"]: r for r in db["VBAK"].aggregate([
            {"$match": {"FISCAL_YEAR": fy1}},
            {"$group": {"_id": "$KUNNR", "NAME1": {"$first": "$NAME1"}, "rev": {"$sum": "$NETWR"}}}
        ])}
        d2 = {r["_id"]: r for r in db["VBAK"].aggregate([
            {"$match": {"FISCAL_YEAR": fy2}},
            {"$group": {"_id": "$KUNNR", "NAME1": {"$first": "$NAME1"}, "rev": {"$sum": "$NETWR"}}}
        ])}
        growth = []
        for k, r in d2.items():
            if k in d1 and d1[k]["rev"] > 0:
                pct = (r["rev"] - d1[k]["rev"]) / d1[k]["rev"] * 100
                if pct > thresh:
                    growth.append({"name": r["NAME1"], "fy1": d1[k]["rev"], "fy2": r["rev"], "pct": pct})
        growth.sort(key=lambda x: x["pct"], reverse=True)
        lines = [f"Customers with >{thresh:.0f}% growth ({fy1} → {fy2}):\n"]
        if not growth:
            lines.append("  No customers found with this growth threshold.")
        for r in growth:
            lines.append(f"  • {r['name']:35s}  {fy1}: ₹{r['fy1']:>12,.0f}  →  {fy2}: ₹{r['fy2']:>12,.0f}  |  {r['pct']:>+.1f}%")
        result = "\n".join(lines)

    elif sub == "product_margins":
        rows = list(db["VBAP"].aggregate([
            {"$group": {"_id": "$MATNR", "ARKTX": {"$first": "$ARKTX"},
                        "avg_margin": {"$avg": "$MARGIN_PCT"}, "total_rev": {"$sum": "$NETWR"}}},
            {"$sort": {"avg_margin": 1}}, {"$limit": n}
        ]))
        lines = [f"{n} products with least margins:\n"]
        for i, r in enumerate(rows, 1):
            lines.append(f"  {i}. {r['ARKTX']:40s}  Avg Margin: {r['avg_margin']:>5.1f}%  |  Revenue: ₹{r['total_rev']:>12,.0f}")
        result = "\n".join(lines)

    elif sub == "company_product":
        rows = list(db["VBAP"].aggregate([
            {"$group": {"_id": {"kunnr": "$KUNNR", "matnr": "$MATNR"},
                        "NAME1": {"$first": "$NAME1"}, "ARKTX": {"$first": "$ARKTX"},
                        "revenue": {"$sum": "$NETWR"}}},
            {"$sort": {"revenue": -1}}, {"$limit": n}
        ]))
        lines = [f"Top {n} company-product combinations by revenue:\n"]
        for i, r in enumerate(rows, 1):
            lines.append(f"  {i:2}. {r['NAME1']:30s}  |  {r['ARKTX']:35s}  |  ₹{r['revenue']:>12,.0f}")
        result = "\n".join(lines)

    elif sub == "manager_growth":
        d1 = {r["_id"]: r["rev"] for r in db["VBAK"].aggregate([
            {"$match": {"FISCAL_YEAR": fy1}},
            {"$group": {"_id": "$AREA_MGR", "rev": {"$sum": "$NETWR"}}}
        ])}
        d2 = {r["_id"]: r["rev"] for r in db["VBAK"].aggregate([
            {"$match": {"FISCAL_YEAR": fy2}},
            {"$group": {"_id": "$AREA_MGR", "rev": {"$sum": "$NETWR"}}}
        ])}
        growth = []
        for am, rev2 in d2.items():
            if am in d1 and d1[am] > 0:
                pct = (rev2 - d1[am]) / d1[am] * 100
                growth.append({"am": am, "fy1": d1[am], "fy2": rev2, "pct": pct})
        growth.sort(key=lambda x: x["pct"])
        lines = [f"Area manager growth ({fy1} → {fy2}), slowest first:\n"]
        for r in growth:
            lines.append(f"  {r['am']:25s}  {fy1}: ₹{r['fy1']:>12,.0f}  →  {fy2}: ₹{r['fy2']:>12,.0f}  |  {r['pct']:>+.1f}%")
        result = "\n".join(lines)

    elif sub == "order_status":
        smap  = {"open": "A", "in process": "B", "in-process": "B", "completed": "C"}
        gbstk = smap.get(str(status).lower(), "A")
        rows  = list(db["VBAK"].find({"GBSTK": gbstk},
                     {"VBELN":1,"NAME1":1,"NETWR":1,"ERDAT":1,"FISCAL_YEAR":1,"_id":0}))
        lines = [f"Found {len(rows)} {status} sales orders:\n"]
        for r in rows:
            lines.append(f"  • {r['VBELN']}  |  {r['NAME1']}  |  ₹{r['NETWR']:,.2f}  |  {r['FISCAL_YEAR']}  |  {r['ERDAT']}")
        result = "\n".join(lines)

    elif sub == "delivery_status":
        smap  = {"pending": "A", "not started": "A", "partial": "B", "completed": "C"}
        lfgsx = smap.get(str(status).lower(), "A")
        rows  = list(db["LIKP"].find({"LFGSX": lfgsx},
                     {"VBELN":1,"NAME1":1,"WADAT":1,"VBELN_VK":1,"_id":0}))
        lines = [f"Found {len(rows)} deliveries (status: {status}):\n"]
        for r in rows:
            lines.append(f"  • {r['VBELN']}  |  {r['NAME1']}  |  Ref: {r['VBELN_VK']}  |  Planned: {r['WADAT']}")
        result = "\n".join(lines)

    elif sub == "billing_status":
        smap  = {"open": "A", "not cleared": "A", "partial": "B", "cleared": "C"}
        rfbsk = smap.get(str(status).lower(), "A")
        rows  = list(db["VBRK"].find({"RFBSK": rfbsk, "FKSTO": {"$ne": "X"}},
                     {"VBELN":1,"NAME1":1,"NETWR":1,"MWSBP":1,"ERDAT":1,"_id":0}))
        lines = [f"Found {len(rows)} billing documents (status: {status}):\n"]
        for r in rows:
            total = round(r["NETWR"] + r["MWSBP"], 2)
            lines.append(f"  • {r['VBELN']}  |  {r['NAME1']}  |  ₹{total:,.2f}  |  {r['ERDAT']}")
        result = "\n".join(lines)

    elif sub == "revenue_by_fy":
        rows = list(db["VBAK"].aggregate([
            {"$group": {"_id": "$FISCAL_YEAR", "total": {"$sum": "$NETWR"}, "count": {"$sum": 1}}},
            {"$sort": {"_id": 1}}
        ]))
        lines = ["Revenue by fiscal year:\n"]
        for r in rows:
            lines.append(f"  {r['_id']}:  {r['count']} orders  |  ₹{r['total']:>15,.2f}")
        result = "\n".join(lines)

    elif sub == "orders_above" and amount:
        rows  = list(db["VBAK"].find({"NETWR": {"$gt": float(amount)}, "GBSTK": "A"},
                     {"VBELN":1,"NAME1":1,"NETWR":1,"VDATU":1,"_id":0}).sort("NETWR", -1))
        lines = [f"Found {len(rows)} open orders above ₹{float(amount):,.0f}:\n"]
        for r in rows:
            lines.append(f"  • {r['VBELN']}  |  {r['NAME1']}  |  ₹{r['NETWR']:,.2f}  |  Delivery: {r['VDATU']}")
        result = "\n".join(lines)

    else:
        result = f"Sub-type '{sub}' not matched — routing to hybrid search."

    return {**state, "tool_result": result, "mongo_query": mongo_q}

# ══════════════════════════════════════════════════════════════════════════════
# NODE 2B — LOOKUP TOOL (Model 2)
# ══════════════════════════════════════════════════════════════════════════════
def node_lookup(state: AgentState) -> AgentState:
    entity_id = str(state["params"].get("entity_id") or "").upper()

    if re.match(r'SO\d+', entity_id):
        doc   = db["VBAK"].find_one({"VBELN": entity_id}, {"_id": 0})
        items = list(db["VBAP"].find({"VBELN": entity_id}, {"_id": 0}))
        if doc:
            smap  = {"A": "Open", "B": "In-Process", "C": "Completed"}
            lines = [f"Sales Order {entity_id}:\n",
                     f"  Customer    : {doc.get('NAME1')}",
                     f"  Date        : {doc.get('ERDAT')}",
                     f"  Fiscal Year : {doc.get('FISCAL_YEAR')}",
                     f"  Net Value   : ₹{doc.get('NETWR', 0):,.2f}",
                     f"  GST (18%)   : ₹{doc.get('MWSBP', 0):,.2f}",
                     f"  Total       : ₹{round(doc.get('NETWR',0)+doc.get('MWSBP',0),2):,.2f}",
                     f"  Status      : {smap.get(doc.get('GBSTK',''), 'Unknown')}",
                     f"  Area Mgr    : {doc.get('AREA_MGR', 'N/A')}",
                     f"\n  Line Items ({len(items)}):"]
            for item in items:
                lines.append(f"    • {item.get('ARKTX'):40s}  Qty: {item.get('KWMENG')} {item.get('MEINS')}  |  ₹{item.get('NETWR',0):,.2f}  |  Margin: {item.get('MARGIN_PCT',0):.1f}%")
            result = "\n".join(lines)
        else:
            result = f"Sales order {entity_id} not found."

    elif re.match(r'C\d+', entity_id):
        doc    = db["KNA1"].find_one({"KUNNR": entity_id}, {"_id": 0})
        orders = list(db["VBAK"].find({"KUNNR": entity_id}, {"_id": 0}))
        if doc:
            total_rev = sum(o.get("NETWR", 0) for o in orders)
            result = (f"Customer {entity_id}:\n"
                      f"  Name      : {doc.get('NAME1')}\n"
                      f"  City      : {doc.get('ORT01')}\n"
                      f"  Region    : {doc.get('REGION')}\n"
                      f"  Area Mgr  : {doc.get('AREA_MGR')}\n"
                      f"  Territory : {doc.get('TERRITORY')}\n"
                      f"  GST No    : {doc.get('STCEG')}\n"
                      f"  Orders    : {len(orders)}\n"
                      f"  Total Rev : ₹{total_rev:,.2f}")
        else:
            result = f"Customer {entity_id} not found."

    elif re.match(r'BI\d+', entity_id):
        doc = db["VBRK"].find_one({"VBELN": entity_id}, {"_id": 0})
        if doc:
            smap   = {"A": "Open", "B": "Partial", "C": "Cleared"}
            result = (f"Billing Document {entity_id}:\n"
                      f"  Customer   : {doc.get('NAME1')}\n"
                      f"  Date       : {doc.get('ERDAT')}\n"
                      f"  Net Value  : ₹{doc.get('NETWR',0):,.2f}\n"
                      f"  GST        : ₹{doc.get('MWSBP',0):,.2f}\n"
                      f"  Total      : ₹{round(doc.get('NETWR',0)+doc.get('MWSBP',0),2):,.2f}\n"
                      f"  Accounting : {smap.get(doc.get('RFBSK',''), 'Unknown')}\n"
                      f"  Cancelled  : {'Yes' if doc.get('FKSTO') == 'X' else 'No'}")
        else:
            result = f"Billing document {entity_id} not found."

    elif re.match(r'DL\d+', entity_id):
        doc = db["LIKP"].find_one({"VBELN": entity_id}, {"_id": 0})
        if doc:
            smap   = {"A": "Not Started", "B": "Partial", "C": "Completed"}
            result = (f"Delivery {entity_id}:\n"
                      f"  Customer   : {doc.get('NAME1')}\n"
                      f"  Ref Order  : {doc.get('VBELN_VK')}\n"
                      f"  Planned GI : {doc.get('WADAT')}\n"
                      f"  Actual GI  : {doc.get('WADAT_IST')}\n"
                      f"  Status     : {smap.get(doc.get('LFGSX',''), 'Unknown')}\n"
                      f"  Weight     : {doc.get('BTGEW')} {doc.get('GEWEI')}")
        else:
            result = f"Delivery {entity_id} not found."

    else:
        return node_hybrid_search(state)

    return {**state, "tool_result": result}

# ══════════════════════════════════════════════════════════════════════════════
# NODE 2C — HYBRID SEARCH (Vector + Text + RRF) — Model 2
# ══════════════════════════════════════════════════════════════════════════════
def reciprocal_rank_fusion(lists: list, k: int = 60) -> list:
    scores, texts = {}, {}
    for results in lists:
        for rank, doc in enumerate(results, start=1):
            did = doc["id"]
            if did not in scores:
                scores[did] = 0.0
                texts[did]  = doc["text"]
            scores[did] += 1.0 / (k + rank)
    return [{"id": d, "text": texts[d], "score": scores[d]}
            for d in sorted(scores, key=lambda x: scores[x], reverse=True)]

def get_tables(question: str) -> list:
    q = question.lower()
    if any(w in q for w in ["margin", "cost", "profit"]):             return ["VBAP", "VBRP"]
    if any(w in q for w in ["manager", "region", "area", "territory"]):return ["VBAK", "KNA1"]
    if any(w in q for w in ["order", "sales"]):                        return ["VBAK", "VBAP"]
    if any(w in q for w in ["deliver", "shipment"]):                   return ["LIKP", "LIPS"]
    if any(w in q for w in ["bill", "invoice"]):                       return ["VBRK", "VBRP"]
    if any(w in q for w in ["customer", "client"]):                    return ["KNA1", "KNVV"]
    return ["VBAK", "VBAP", "VBRK", "KNA1"]

def node_hybrid_search(state: AgentState) -> AgentState:
    question = state["question"]
    tables   = get_tables(question)

    # vector search
    vec = []
    for t in tables:
        for doc in vectordb.similarity_search(question, k=5, filter={"table": t}):
            vec.append({"id": f"{t}_{hash(doc.page_content)}", "text": doc.page_content})

    # text search
    txt = []
    for t in [x for x in tables if x in ["VBAK","VBAP","VBRK","KNA1","LIKP"]]:
        try:
            for doc in db[t].find({"$text": {"$search": question}},
                                   {"score": {"$meta": "textScore"}, "_id": 0}
                                  ).sort([("score", {"$meta": "textScore"})]).limit(5):
                text = " | ".join(f"{k}: {v}" for k, v in doc.items() if k != "score" and v)
                txt.append({"id": f"{t}_t_{hash(text)}", "text": text[:500]})
        except Exception:
            pass

    fused   = reciprocal_rank_fusion([vec, txt])[:10]
    context = "\n\n---\n\n".join(r["text"] for r in fused)
    return {**state, "tool_result": context}

# ══════════════════════════════════════════════════════════════════════════════
# NODE 3 — FORMAT RESPONSE (Model 2)
# Model 2 formats final answer — sees SAP data, always local
# Also includes the ABAP query generated by Model 1
# ══════════════════════════════════════════════════════════════════════════════
def node_format(state: AgentState) -> AgentState:
    intent      = state["intent"]
    tool_result = state["tool_result"]
    question    = state["question"]
    abap        = state["abap_query"]

    if intent == "semantic":
        prompt = PromptTemplate(
            template="""You are an SAP SD assistant. Answer using ONLY the records below.
Status: GBSTK A=Open B=In-Process C=Completed | RFBSK A=Open B=Partial C=Cleared
Currency: INR | Fiscal Year: Indian Apr-Mar

SAP Records:
{context}

Question: {question}
Answer:""",
            input_variables=["context", "question"]
        )
        answer = (prompt | llm_2 | StrOutputParser()).invoke({
            "context": tool_result, "question": question
        })
    else:
        prompt = PromptTemplate(
            template="""You are an SAP data analyst. Your ONLY job is to reformat the data below as bullet points.

STRICT RULES:
- Copy EVERY single line from SAP Data — do NOT skip any line
- Do NOT combine any entries
- Do NOT summarize or calculate
- Do NOT add or remove any numbers
- Keep exact names and values as shown
- Format each line starting with "• "

SAP Data:
{data}

Question: {question}

Bullet point list (include ALL lines, do not stop early):""",
            input_variables=["data", "question"]
        )
        answer = (prompt | llm_2 | StrOutputParser()).invoke({
            "data": tool_result, "question": question
        })

    # append ABAP query to answer
    mongo_q = state.get("mongo_query", "")
    final   = (
        f"{answer}\n\n"
        f"---\n"
        f"MongoDB Query:\n{mongo_q}\n\n"
        f"ABAP Query:\n{abap}"
    )
    return {**state, "final_answer": final}

# ══════════════════════════════════════════════════════════════════════════════
# ROUTER
# ══════════════════════════════════════════════════════════════════════════════
def route(state: AgentState) -> Literal["node_aggregate","node_lookup","node_hybrid_search"]:
    intent = state.get("intent", "semantic")
    if intent == "aggregate": return "node_aggregate"
    if intent == "lookup":    return "node_lookup"
    return "node_hybrid_search"

# ══════════════════════════════════════════════════════════════════════════════
# BUILD LANGGRAPH
# ══════════════════════════════════════════════════════════════════════════════
def build_agent():
    g = StateGraph(AgentState)
    g.add_node("node_classify",      node_classify)       # Model 1
    g.add_node("node_aggregate",     node_aggregate)      # Model 2
    g.add_node("node_lookup",        node_lookup)         # Model 2
    g.add_node("node_hybrid_search", node_hybrid_search)  # Model 2
    g.add_node("node_format",        node_format)         # Model 2
    g.set_entry_point("node_classify")
    g.add_conditional_edges("node_classify", route, {
        "node_aggregate":     "node_aggregate",
        "node_lookup":        "node_lookup",
        "node_hybrid_search": "node_hybrid_search",
    })
    g.add_edge("node_aggregate",     "node_format")
    g.add_edge("node_lookup",        "node_format")
    g.add_edge("node_hybrid_search", "node_format")
    g.add_edge("node_format",        END)
    return g.compile()

agent = build_agent()

# ══════════════════════════════════════════════════════════════════════════════
# PUBLIC API
# ══════════════════════════════════════════════════════════════════════════════
def query_sap(question: str, verbose: bool = False) -> str:
    result = agent.invoke({
        "question":     question,
        "intent":       "",
        "sub_type":     "",
        "params":       {},
        "abap_query":   "",
        "mongo_query":  "",
        "tool_result":  "",
        "final_answer": "",
        "messages":     []
    })
    if verbose:
        print(f"  [Model 1 classified → Intent: {result['intent']} | Sub-type: {result['sub_type']}]")
        print(f"  [ABAP generated by Model 1, MongoDB executed by Model 2]")
    return result["final_answer"]

# ══════════════════════════════════════════════════════════════════════════════
# TERMINAL
# ══════════════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    print("\n" + "="*65)
    print("  SAP SD Intelligent Agent")
    print(f"  Model 1: {MODEL_1}  (classify + ABAP)")
    print(f"  Model 2: {MODEL_2}  (execute + format)")
    print(f"  Embed  : {EMBED_MODEL}")
    print("="*65)
    print("Type 'verbose' to see debug info | 'quit' to exit\n")

    verbose = False
    while True:
        try:
            q = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nGoodbye!"); break
        if not q: continue
        if q.lower() in ["quit", "exit", "q"]: print("Goodbye!"); break
        if q.lower() == "verbose":
            verbose = not verbose
            print(f"  [Verbose: {'ON' if verbose else 'OFF'}]\n")
            continue
        print(f"\nAssistant: {query_sap(q, verbose)}\n")
        print("-"*65 + "\n")